n = input('Digite algo = ')
print(f'O tipo primitivo é = {type(n)}')
print(f'É alfanumerico? = {n.isalpha()}')
print(f'É numerico? = {n.isnumeric()}')
print(f'É ascii? = {n.isascii()}')
print(f'É minusculo? = {n.islower()}')
print(f'É maisculo? = {n.isupper()}')
print(f'É decimal? = {n.isdecimal()}')
print(f'É digito? = {n.isdigit()}')
